name: Test Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to test publish'
        required: true
        default: 'pyconfbox'
        type: choice
        options:
          - pyconfbox
          - pyconfbox-django
          - pyconfbox-mysql
          - pyconfbox-postgresql
          - pyconfbox-mongodb

jobs:
  test-publish:
    runs-on: ubuntu-latest
    environment: test-pypi
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Build package
        run: |
          cd packages/${{ github.event.inputs.package }}
          python -m build
      
      - name: Check distribution
        run: |
          cd packages/${{ github.event.inputs.package }}
          twine check dist/*
      
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          cd packages/${{ github.event.inputs.package }}
          twine upload --repository testpypi dist/* --skip-existing 