name: Test Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to test publish'
        required: true
        default: 'pyconfbox'
        type: choice
        options:
          - pyconfbox
          - pyconfbox-django
          - pyconfbox-mysql
          - pyconfbox-postgresql
          - pyconfbox-mongodb

jobs:
  test-publish:
    runs-on: ubuntu-latest
    environment: test-pypi
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Build package
        run: |
          uv build packages/${{ github.event.inputs.package }}
      
      - name: Check distribution
        run: |
          uv tool run twine check packages/${{ github.event.inputs.package }}/dist/*
      
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          uv tool run twine upload --repository testpypi packages/${{ github.event.inputs.package }}/dist/* --skip-existing 